name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uuses: docker/build-push-action@<full-commit-sha>
        with:
          push: true
          tags: voa2000/python-app:latest
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  # cd:
  #   needs: ci
  #   runs-on: self-hosted
  #   steps:

  #     - uses: actions/checkout@v3

  #     - name: Modify values file
  #       shell: bash
  #       run: |
  #         echo ${{needs.ci.outputs.commit_id}}
  #         pip install yq
  #         yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml

  #     - name: Commit changes
  #       uses: EndBug/add-and-commit@v9
  #       with:
  #         message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

  #     - name: Install argocd
  #       shell: bash
  #       run: |
  #         curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
  #         chmod +x argocd
  #         sudo mv ./argocd /usr/local/bin/argocd

  #     - name: Argocd app sync
  #       shell: bash
  #       run: |
  #         argocd login argocd-server.argocd \
  #           --insecure  \
  #           --grpc-web \
  #           --username admin \
  #           --password  ${{ secrets.ARGOCD_PASSWORD }}
  #         argocd app sync python-app